package svg

import (
	"fmt"
	"os"
	"regexp"
	"strings"
)

// Stats are the dynamic values that get written into the template
// every run.
type Stats struct {
	Age       string
	Repos     int
	Contrib   int
	Stars     int
	Commits   int
	Followers int
	LOCAdd    int
	LOCDel    int
}

// Rewrite reads an SVG template, replaces the text of every id'd
// <tspan> with the corresponding stat, and re-pads the matching
// "_dots" tspan so the right edge stays aligned. The file is written
// back in place.
func Rewrite(path string, s Stats) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	doc := string(raw)

	// (id, formatted-value, target-width-of-value)
	// width is chosen to mirror Andrew6rant's justify_format() lengths.
	type field struct {
		id    string
		value string
		width int
	}
	loc := s.LOCAdd - s.LOCDel
	fields := []field{
		{"age_data", s.Age, 0},
		{"repo_data", commaInt(s.Repos), 6},
		{"contrib_data", commaInt(s.Contrib), 0},
		{"star_data", commaInt(s.Stars), 14},
		{"commit_data", commaInt(s.Commits), 22},
		{"follower_data", commaInt(s.Followers), 10},
		{"loc_data", commaInt(loc), 9},
		{"loc_add", commaInt(s.LOCAdd), 0},
		{"loc_del", commaInt(s.LOCDel), 0},
	}

	for _, f := range fields {
		var dotsID string
		if f.width > 0 {
			dotsID = f.id + "_dots"
		}
		var derr error
		doc, derr = justify(doc, f.id, dotsID, f.value, f.width)
		if derr != nil {
			return fmt.Errorf("update %s: %w", f.id, derr)
		}
	}

	return os.WriteFile(path, []byte(doc), 0o644)
}

// justify replaces the text of <tspan id="valueID">…</tspan> with
// `value`. If dotsID is non-empty, it also recomputes the leading
// "<tspan ... id=dotsID>…</tspan>" with a dot-leader so that
// (dots + value) == targetWidth characters.
//
// This mirrors today.py's justify_format() including the special
// dot_map for very short padding ('', ' ', '. ').
func justify(doc, valueID, dotsID, value string, targetWidth int) (string, error) {
	out, err := replaceTspanText(doc, valueID, value)
	if err != nil {
		return "", err
	}
	if dotsID == "" {
		return out, nil
	}

	just := targetWidth - len(value)
	if just < 0 {
		just = 0
	}
	var dots string
	switch just {
	case 0:
		dots = ""
	case 1:
		dots = " "
	case 2:
		dots = ". "
	default:
		dots = " " + strings.Repeat(".", just) + " "
	}
	return replaceTspanText(out, dotsID, dots)
}

// replaceTspanText finds the (single) <tspan ... id="ID" ...>BODY</tspan>
// and substitutes BODY with newText. The tspan's own attributes are
// preserved verbatim.
//
// We use a regexp rather than a real XML parser because:
//   - the template is generated by us, so tspans containing the id are
//     guaranteed to be flat (no nested tags);
//   - re-serialising the SVG via encoding/xml would normalise whitespace
//     inside <text>, which would shift the ASCII art and break alignment.
func replaceTspanText(doc, id, newText string) (string, error) {
	// Match <tspan ... id="ID" ...>BODY</tspan> with non-greedy body.
	pat := fmt.Sprintf(`(<tspan[^>]*\bid="%s"[^>]*>)([^<]*)(</tspan>)`, regexp.QuoteMeta(id))
	re := regexp.MustCompile(pat)
	if !re.MatchString(doc) {
		return "", fmt.Errorf("tspan id=%q not found", id)
	}
	escaped := escapeXML(newText)
	// Use a literal replacement to avoid $1/$2 surprises in `escaped`.
	return re.ReplaceAllStringFunc(doc, func(match string) string {
		parts := re.FindStringSubmatch(match)
		return parts[1] + escaped + parts[3]
	}), nil
}

// commaInt formats an int with thousands separators, e.g. 1234567 -> "1,234,567".
func commaInt(n int) string {
	neg := n < 0
	if neg {
		n = -n
	}
	s := fmt.Sprintf("%d", n)
	// Insert commas from the right.
	var b strings.Builder
	for i, r := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			b.WriteByte(',')
		}
		b.WriteRune(r)
	}
	if neg {
		return "-" + b.String()
	}
	return b.String()
}
